# Generated by Django 2.0.2 on 2018-10-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, '超级管理员'), (2, '管理员'), (3, '普通用户')], help_text='权限标识', null=True, verbose_name='权限标识'),
        ),
    ]
